- .gitignore
The Asset Library application for FuncGodot has been [rejected](https://godotengine.org/asset-library/asset/edit/11253) because the repo lacks a `.gitignore`. I have added the template `.gitignore` file from the official docs. After this change the package can be resubmitted for inclusion.
> Create .gitignore to comply with Godot Asset Library requirements

- addons/func_godot/src/map/func_godot_map_settings.gd
- addons/func_godot/src/util/func_godot_texture_loader.gd
Allows you to assign an ORMMaterial3D as the default material to use ORM maps in place of standalone AO, metallic and roughness maps.
> Implement support for ORMMaterial3D

- addons/func_godot/src/fgd/func_godot_fgd_model_point_class.gd
Fixes an issue where Godot would not allow ModelPointClass or PointClass resources to be loaded into the project.
When the build_def_text() function was updated to prefer an enum of editors instead of a bool, this wasn't updated in ModelPointClass, which uses `super()`, which prevented PointClass from loading as well. This prevented any PointClass resources or any classes extending it from being added to new projects using Godot 4.2.2 stable and this latest github repository.
> Failed to load script "res://addons/func_godot/src/fgd/func_godot_fgd_model_point_class.gd" with error "Parse Error". (User)
> Cannot get class 'FuncGodotFGDPointClass'. editor/create_dialog.cpp:271 - Condition "inherits.is_empty()" is true.
New PointClass resources were not available in the resource list, new …
> Fix outdated build_def_text() signature on ModelPointClass

- addons/func_godot/src/core/func_godot.gd
- addons/func_godot/src/map/func_godot_map.gd
- addons/func_godot/src/map/func_godot_map_settings.gd
FuncGodotMapSettings now has a private property `scale_factor`, which gets updated in `inverse_scale_factor`'s new setter method. Map Settings has been turned into a tool script to facilitate this. The purpose is to replace all instances of division in the build process with multiplication, to squeeze a bit more performance out of the build.
On top of this, FuncGodotMap's `apply_properties_and_finish()` method has had an unnecessary entity loop removed and the contents of the loop moved to the remaining entity loop. An array of dictionaries was able to be removed as a result. Additionally, the direct call to `_func_godot_apply_properties()` has been replaced with a call via String, to better ensure that the correct override is called in the event of inheriting classes.
> Map build optimizations

- addons/func_godot/src/fgd/func_godot_fgd_entity_class.gd
- addons/func_godot/src/map/func_godot_map.gd
Adds a override_node_properties bool to FGD Entity. Map generator read apply this value directly to a node if there is a matching property name. If that property is a different type, it will cause an map build error.
> Allows automatically applying Node properties directly to the Node. 

- addons/func_godot/src/core/func_godot.gd
- addons/func_godot/src/core/func_godot_map_data.gd
- addons/func_godot/src/core/func_godot_surface_gatherer.gd
- addons/func_godot/src/fgd/func_godot_fgd_solid_class.gd
- addons/func_godot/src/map/func_godot_map.gd
These options can propagate data necessary for getting the texture on the part of a mesh corresponding to a collision.
Added as per discussion https://github.com/orgs/func-godot/discussions/59
Outstanding questions / known issues:
- I haven't tested this at runtime yet, so I'm sure there are some math issues. I'll get to that later this week, hopefully.
- I am uncertain if my method of finding average / center position for faces is correct. I'll find out when I test later, but please lmk if it is clearly wrong.
- The `shape_index_to_faces_range_map` provides redundant information for concave meshes, but currently it still gets built for them and then thrown away.
- I am passing scale factor to the surface gatherer so that it can do the map file -> godot translation in the loop. Feels like …
> Add options for building mesh/collision data into metadata of generated nodes

- addons/func_godot/src/core/func_godot_geo_generator.gd
Default values for entity mins and maxs used to be Vector3.ZERO, but this would cause problems when vertex components were either all positive or all negative values.
Resolved by setting the default values to Vector3.INF and setting the initial mins and maxs in origin calcs to the first vertex.
A handler is also in place in the event that there are no vertices in the current SolidEntity.
> Fix Solid Entity Bounds Origin Generation

- addons/func_godot/src/func_godot_plugin.gd
- addons/func_godot/src/map/func_godot_map.gd
Adds Map Settings to Project Settings so you dont have to manually change the map settings each time a new Func Godot Map is added to a scene
> add map settings property

- addons/func_godot/src/core/func_godot_geo_generator.gd
`CMP_EPSILON` was not small enough to allow extremely shallow face plane normals to be returned, causing them to be skipped in the build process despite returning a valid cross product.
Swapping the return statements and switching the conditional to check for valid cross products (anything greater than zero) rather than invalid ones fixes this issue for *most* shallow brushes made in a map editor. Certain extreme cases are still not caught but that may require a rework of GeoGenerator rather than a simple bug fix.
> Fix Shallow Faces Not Being Built

- addons/func_godot/src/trenchbroom/trenchbroom_game_config.gd
TrenchBroom 2024.2 went stable shortly after FuncGodot 2024.3.1 released. This PR updates FuncGodot to use Version 9 as the Latest GameConfig version in the TrenchbroomGameConfig resource.
> Change TrenchbroomGameConfig Default to Version 9

- addons/func_godot/src/fgd/func_godot_fgd_entity_class.gd
Previously entity descriptions were explicitly limited to no special or escape characters. There seemed to be an assumption that the FGD format may not have supported escape characters. Additionally there was an unnecessary replacement of the `\n` escape character as it was immediately followed up by `strip_edges()` which removes `\n` anyway. There was also a superfluous check for the `@BaseClass` prefix value, which was already checked for in a previous conditional.
This PR changes the way the description is processed to only replace the one unsupported escape character: `\"` (descriptions are encapsulated by quote marks, and the FGD format doesn't actually support escape characters, Godot converts them when writing to the FGD file). All other escape characters and symbols appear to be …
> Allow More Flexible Formatting in Entity Descriptions

- addons/func_godot/src/func_godot_plugin.gd
This PR fixes an error message being displayed when closing Godot editor or disabling func_godot plugin in the project settings: 
` scene/main/node.cpp:1602 - Condition "p_child->data.parent != this" is true.`
> Fix invalid container id when unregistering progress bar control

- addons/func_godot/src/fgd/func_godot_fgd_entity_class.gd
I ran into an issue recently where I noticed that whenever I tried to load an FGD into TrenchBroom that had been generated with an object as a value, TrenchBroom would complain about the FGD being incorrectly formatted.
The error is:
```Could not load builtin entity definition file '"min-reprod.fgd"': At line 41, column 22: Expected integer, decimal, string, or ':', but got word (raw data: 'res')```
I've provided what I believe to be a minimal reproduction Godot project of the issue.
This PR just adds a couple of double quotes around the value, which fixes the aforementioned issue.
[Fg-min-reprod-object.zip](https://github.com/user-attachments/files/19617559/Fg-min-reprod-object.zip)
> Fix resource (materials, sounds, etc.) values not being strings in FGD files

- addons/func_godot/src/map/func_godot_map.gd
Adds support for providing custom classes to entities via Node Generation -> Node Class, `ClassDB` doesn't register custom classes, but using this method we can ensure they are found.
> Add support for custom classes

- addons/func_godot/src/netradiant_custom/netradiant_custom_gamepack_config.gd
This PR adds minor support to NetRadiant Custom configurations for adjusting the output "maptype" string in preparation for PatchDef2 support.
In addition: to export NRC shader definitions properly, the `.shader` and `shaderlist.txt` should go in the game engine path.
For now, I'm leaving the export to NRC as well, so it can easily be repackaged for distribution and supporting any legacy gamepacks that somehow worked with this.
> NetRadiant Custom: Add maptype selection; fix shader output directories and spelling errors

- addons/func_godot/src/fgd/func_godot_fgd_model_point_class.gd
Model Point Class originally performed an auto rotation to the output model due to the differences between Quake's and Godot's coordinate systems (Quake uses +X forward while Godot uses -Z forward).
TrenchBroom recently changed how they display GLTF models, orienting them by having a GLTF model's +Z point towards +X.
https://github.com/TrenchBroom/TrenchBroom/pull/4843
This has the effect of nullifying the corrective rotation performed by Model Point Class, causing exported models in TrenchBroom to be oriented incorrectly.
However, FuncGodot is intended to be as editor agnostic as possible, and other editors like NetRadiant-Custom do not currently perform this rotation correction.
Additionally, FuncGodot using a hardcoded rotation assumes that developers will have their characters and …
> Add Rotation Offset Property to Model Point Class

- addons/func_godot/func_godot_local_config.tres
- addons/func_godot/src/util/func_godot_local_config.gd
This PR changes "Export Func Godot Settings" and "Reload Func Godot Settings" from checkboxes to buttons.
It's not very intuitive that checking a checkbox would do some action, but it's more obvious with buttons.
> Change export_func_godot_settings and reload_func_godot_settings to tool buttons

- addons/func_godot/src/util/func_godot_texture_loader.gd
Texture Loader does not create materials for Skip or Clip textures, as the mesh faces using those textures are removed on build. Origin brushes have their faces removed as well, but the texture is still generated.
This PR changes that by adding an exception for the Origin texture alongside Skip and Clip as intended.
> Prevent Texture Loader from Generating Origin Material

- addons/func_godot/src/core/entity_assembler.gd
Hi, as I'm updating func_godot_scene_import to the latest version, I've run into a small hitch. When importing, the node is not part of the scene tree so get_tree() returns null, and the map fails to build. I don't know when else a scene might not be a part of a scene tree, but this adds a safety check for those circumstances
This is a small safety check, that checks if the map node is part of a scene tree, if it is, it uses that scene root, and if not, it uses itself.
> Minor additional safety check for scene tree in the entity assembler

- addons/func_godot/src/fgd/func_godot_fgd_entity_class.gd
Default values for boolean properties are fully supported, but their default value is not added to the FGD so it is not visible in the editor.
This change would update the FGD from:
```
name(choices) : "description" = 
[
0 : "No"
1 : "Yes"
]
```
to:
```
name(choices) : "description" : 1 = 
[
0 : "No"
1 : "Yes"
]
```
> Export bool property defaults to FGD

- addons/func_godot/src/fgd/func_godot_fgd_entity_class.gd
The documentation and code allows both String and int types as values for choices properties, however when exporting the FGD the value is not quoted, causing parsing errors when the value is of string type.
The fix just quotes the value, which works for both string and int types.
> Fix for string default values in 'choices' properties

- addons/func_godot/src/core/geometry_generator.gd
- Move texture metadata to the mesh building loop to keep all metadata logic in the same place
- Change normals metadata to face normals, rather than vertex normals from the mesh builder
- Use the existing get_centroid function to calculate face positions
- Add vertices using the triangle indices rather than the vertex array from the mesh builder
- Also a tiny whitespace fix on the comments at the end - they were indented too much
To test this I made a simple map with 5 visible quads using 4 different textures. Expectation is  that texture_names has 4 entries, textures/normals/positions all have 5, and vertices has 30 (5 quads -> 10 tris -> 30 verts).
Before:
After:
> Bug fixes for mesh metadata generation

- addons/func_godot/src/map/func_godot_map.gd
Right now, if your game passes map file to FuncGodotMap by UID, during building it will crash with errors
```
ERROR: Invalid UID.
at: (core/io/resource_uid.cpp:154)
ERROR: [MAP] Map file uid://SOMEUID does not exist.
at: push_error (core/variant/variant_utility.cpp:1098)
ERROR: [MAP] Verification failed: Does not exist. Aborting map build
at: push_error (core/variant/variant_utility.cpp:1098)
```
Resolving UID to path in `verify()` resolves this issue.
Personally I'm not even sure why is `verify()` needed, considering `parse_map_data()` in `parser.gd` already verifies itself that everything is correct and map file exists.
> Resolve UID path in verify()

- addons/func_godot/src/fgd/func_godot_fgd_file.gd
I get an error when clicking the Export FGD button for FuncGodotFGDFile. It works fine after clicking Export GameConfig for TrenchBroomGameConfig.
> res://addons/func_godot/src/fgd/func_godot_fgd_file.gd:39 - Cannot call method 'store_string' on a null value.
I was following [this tutorial](https://youtu.be/_FFYBkMka60?t=515) created a year ago and the author had the same error.
It turns out that we are both entering the path manually instead of creating and picking the output directory via the file dialog. Export GameConfig automatically creates the FGD output directory when the directory is missing, whereas Export FGD does not. This PR adds the missing logic.
I also changed manual path concatenation to `path_join()` so it works better when `fgd_output_folder` contains a trailing slash. …
> Fix error when exporting FGD before exporting game config

- addons/func_godot/src/import/quake_map_import_plugin.gd
There is always an error when the editor sees a `*.map` file for the first time:
> ERROR: Cannot open file 'res://.godot/imported/test.map-75dfd93010aa3e622384aaaff66cbb14.tres'.
> ERROR: Failed loading resource: res://.godot/imported/test.map-75dfd93010aa3e622384aaaff66cbb14.tres. Make sure resources have been imported by opening the project in the editor at least once.
This is because the imported resource does not exist yet. So the `load()` call complains about that.
https://github.com/func-godot/func_godot_plugin/blob/93a812e1afa4bb41ec69c1d86c114f2a6c627e8d/addons/func_godot/src/import/quake_map_import_plugin.gd#L36-L41
We can use `ResourceLoader.exists()` to avoid that :smiley:
> Fix error on first map import

- addons/func_godot/fgd/func_detail.tres
- addons/func_godot/fgd/func_detail_illusionary.tres
- addons/func_godot/fgd/func_geo.tres
- addons/func_godot/fgd/func_illusionary.tres
- addons/func_godot/fgd/worldspawn.tres
- addons/func_godot/src/core/entity_assembler.gd
- addons/func_godot/src/core/geometry_generator.gd
- addons/func_godot/src/fgd/func_godot_fgd_solid_class.gd
This re-implements the functionality of the `collision_shape_to_face_range_map` metadata. Since the faces for each brush are no longer contiguous within a mesh, I've changed the metadata type from a range to a list of indices, and also changed the name of the metadata key to match. The configuration variable name should probably be updated to suit the change in data type.
For each face, I store a dictionary to map faces to the list of metadata indices for each triangle of the face. Then, when the collision shapes are generated:
- Convex shapes: when creating the collision shape for a brush, we loop through each face of and collect the metadata indices associated with that brush
- Concave shapes: only one shape is generated per entity, so we can simply collect the whole list of metadata …
> Implement the collision shape to face indices map metadata

- .gitattributes
Added .gitattributes file with [export-ignore](https://git-scm.com/docs/gitattributes#_export_ignore) attributes. When [git archive](https://git-scm.com/docs/git-archive) command is executed, generated archive will not contain files marked by this attribute. [Github relies on this command](https://docs.github.com/en/repositories/working-with-files/using-files/downloading-source-code-archives#overview-of-source-code-archives) when you download source code via website. Considering that Asset Lib directly downloads zip from archive link, then this mean it's similarly affected by export-ignore.
.gitattributes in this PR is configured in a way, that every file is excluded, but when addons folder and it's contents are included back (more precisely, exclamation point changes export-ignore's …
> Include only plugin files for asset lib (.gitattributes)

- addons/func_godot/src/core/entity_assembler.gd
These are functionally equivalent, however `get_tree()` prints an error message if the node is not in the scene tree, whereas `is_inside_tree()` does not. The code seems designed to handle the case where the node isn't in the tree, so it should be better to use the error-free version.
Docs: https://docs.godotengine.org/en/stable/classes/class_node.html#class-node-method-get-tree
I got this error when building a map file at runtime:
```gdscript
var fgm := FuncGodotMap.new()
fgm.map_settings = map_settings
fgm.local_map_file = resource.resource_path
fgm.build() # <- error message printed here: entity_assembler.gd:406 @ build(): Parameter "data.tree" is null.
```
> Use is_inside_tree instead of get_tree to check if the map is in the tree

- addons/func_godot/src/core/entity_assembler.gd
When auto applying matching properties by name as well as auto applying the `scale` property in a point entity, an error is printed when scale is not a Vector3, as it conflicts with the `scale` property on the `Node3D` class. Unlike the other magic properties (e.g. mangle/angle/origin which map to `rotation_degrees` and `position`) the name in the Godot node is the same, so this can't be worked around in user code (except by not using `apply_scale_on_map_build` or `auto_apply_to_matching_node_properties`).
func_godot supports float, string, or Vector types in the `scale` property (so re-doing type conversion is non-trivial), and the scale has already been applied in the `generate_point_entity_node` function, so the easiest way is to simply skip the `scale` property when auto-applying …
> Skip attempting to auto-apply 'scale' property

- addons/func_godot/src/core/data.gd
- addons/func_godot/src/core/entity_assembler.gd
- addons/func_godot/src/core/geometry_generator.gd
- addons/func_godot/src/util/func_godot_util.gd
This PR adds a few small changes to the UV2 unwrap process.
Currently, mesh unwrap occurs in geometry_generator. However, if a mesh is smooth shaded, this is seemingly discarded by the new ArrayMesh returned by `smooth_mesh_by_angle`. So, when a user desired UV2 unwrapping, only non-smoothed meshes would be unwrapped.
This fix should be reverted when smooth shading is moved back into Geometry Generator, as the unwrap would occur after that process already. See the notes in code for more explanation.
As such, if a mesh is detected as using non-disabled global illumination and UV2 unwrap is enabled, it is skipped in GeometryGenerator and instead unwrapped after smoothing in EntityAssembler.
To address typing, `smooth_mesh_by_angle` now returns an ArrayMesh (no code changes, as this is …
> Unwrap UV2 on smooth shaded meshes after smoothing process
